# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\tchallenge\"8\n\x0cHelloRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0c\n\x04sign\x18\x03 \x01(\t\"I\n\nHelloReply\x12%\n\x04resp\x18\x01 \x03(\x0b\x32\x17.challenge.HelloReply.r\x1a\x14\n\x01r\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\tChallenge\x12<\n\x08SayHello\x12\x17.challenge.HelloRequest\x1a\x15.challenge.HelloReply\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_HELLOREPLY_R = _HELLOREPLY.nested_types_by_name['r']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:challenge.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {

  'r' : _reflection.GeneratedProtocolMessageType('r', (_message.Message,), {
    'DESCRIPTOR' : _HELLOREPLY_R,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:challenge.HelloReply.r)
    })
  ,
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:challenge.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)
_sym_db.RegisterMessage(HelloReply.r)

_CHALLENGE = DESCRIPTOR.services_by_name['Challenge']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=25
  _HELLOREQUEST._serialized_end=81
  _HELLOREPLY._serialized_start=83
  _HELLOREPLY._serialized_end=156
  _HELLOREPLY_R._serialized_start=136
  _HELLOREPLY_R._serialized_end=156
  _CHALLENGE._serialized_start=158
  _CHALLENGE._serialized_end=231
# @@protoc_insertion_point(module_scope)
